### ISSUE TITLE
Failed to load the cursor-count package

### ISSUE THREAD

**Issue by eranimo** [paradoxxxzero/cursor-count#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.2
**Thrown From**: [cursor-count](https://github.com/paradoxxxzero/cursor-count) package, v0.2.0
### Stack Trace

Failed to load the cursor-count package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/kaelan/.atom/packages/cursor-count/lib/cursor-count-view.coffee:5:199)
    at /Users/kaelan/.atom/packages/cursor-count/lib/cursor-count-view.coffee:10:5
    at Object.<anonymous> (/Users/kaelan/.atom/packages/cursor-count/lib/cursor-count-view.coffee:50:5)
    at Object.<anonymous> (/Users/kaelan/.atom/packages/cursor-count/lib/cursor-count-view.coffee:52:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "terminal",
      "tree-view-open-files",
      "linter-csslint",
      "linter-scss-lint",
      "linter-jscs",
      "eslint",
      "linter-jshint"
    ],
    "themes": [
      "flatland-dark-ui",
      "flatland-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
auto-detect-indentation, v0.4.2
color-picker, v2.0.4
cursor-count, v0.2.0
emmet, v2.3.10
file-icons, v1.5.7
flatland-dark, v0.1.6
flatland-dark-ui, v0.2.4
highlight-selected, v0.9.3
language-ejs, v0.1.0
less-than-slash, v0.6.0
linter, v0.12.6
linter-coffeelint, v0.3.2
linter-eslint, v0.5.8
linter-less, v0.5.0
linter-pylint, v0.2.2
react, v0.12.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by serapath** [comment]
check https://atom.io/packages/cursor-indicator
